version: '3'
services: 
    web:
        build:  .
        command: /app/entrypoint.sh
        ports:
            - 8000:8000
        depends_on: 
            - db
    
    db:
        image: postgres
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"